#                 ........        ..........              ............   .....................               
#               ...@@@^*...      ..,@@@@\*................,]]@@@@\]**.....]]]]/@@@@@@@@@@@]*...              
#               ..=@O@@O^*..     ..=@OO@@O\*@@@]]]`,]/@@@OOOOOOOOOO@@@\`@@OOOOOOOOOOOOO@@@@@`...             
#              ..*@OO@@Oo*..     ..=@OO@@@O`=@@OOOOOOOOOOOO@@@@@@@@@@Oooo@OOOO@@@@@@@@@@@OO/*...             
#              ..=@OO@@Oo*..     ..=@OO@@@O**o@@OO@@@@@@@OO@@@@@OOOOo/`*,O@@@@@@@@@OOOOo[`*....              
#             ..*@OOO@@O^..      ..=@OO@@@o*.*\O@@@@@@@@@OOO@@O/*........*,\O@@@@Oo`*........                
#             ..=@OO@@@O^..      .*@@OO@@@o*...*[[o/[[[O@OOO@@O^..      ....*@@@OO^..                        
#            ..*@@OO@@@O*..     ..*@@OO@@@o*..........*=@OOO@@O^..        ..=@O@OO^*.......                  
#            ..=@OOO@@@O*..     ..*@@OO@@@O*..      ..*@@OOO@@O^..       ..*@@O@@@@@@@@\]*....               
#            .*/@OOO@@Oo*..     ..*@OOO@@@O*..      ..*@@OO@@@O^..       ..=@OO@OOOOOOOO@@^*..               
#           ..*@@OOO@@Oo*.      ..=@OOOO@@O*..      ..=@OOO@@@O*..      ..*@OOOO@@@@@@@@@Oo*..               
#           ..*@@OOO@@O^*.      ..=@OOO@@@O*..      ..=@OOO@@@O*..     .../@OO@@@@@@@OOOo[*...               
#           ..*@@OOO@@O^..      ..=@OOO@@Oo*..      .*@@OOO@@@O*..     ..=@OO@@@OO/[***......                
#           ..*O@OOO@@O^*.      ..=@OO@@@O^..      ..*@@OOO@@@O*..    ..*@@OO@@Oo*.....                      
#            .*=@@OOO@@O*..    ..,@@O@@@O/*..      ..*@OOOO@@@o*..    ..,@OO@@@O^..........                  
#            ..*O@@OOO@@O`.....*/@OOO@@OO*..       ..*O@OOO@@Oo*.     .*@@OO@@OO`***]]]]`*.....              
#             ..,O@@@OOO@@@@@@@@OOO@@@@O`..         ..=@@OO@@O^*.    ..*@@O@@@@@@@OOOOOOO@@O]*...            
#             ...*\O@@@OOOOOOOOO@@@@@Oo*...         ..*\@@@@@O^..    ..*@OOOOOOOOOOOOOOOO@@@@@\`..           
#               ...*,OO@@@@@@@@@@@@Oo`....           ..*,OO@O/*..    ..*O@@@@@@@@@@@@@@@@@@@OO^*..           
#                 ....*[oOOOOOOOOo[*....              ....***....    ...*\OOOO@OOOOOOOooo[[[`*....           
#                    .....*****......                   .......       .....*******..............             
#                          ...                                              ....                             
#语言-可用的官方语言：zh_cn,zh_tw,en_us
language: 'zh_cn.yml'
#Bar设置##########################################################
bar:
  enable: true   #是否开启Boss血量条显示固有属性
  fresh: 10   #Bar多少刻刷新一次
#食物设置##########################################################
food:
  hunger: 
    speed: 30   #每多少秒固定减少1点饥饿值
  rotten: 
    enable: true   #是否打开食物腐烂机制
    speed: 30   #每多少秒计算一次腐烂-1
item:
  sawer: 
    enable: true   #是否开启内置物品掉落有标识的功能
  blowarrow:
    autoclear: 20   #吹箭卡在方块中多少秒自动清除
#玩家设置##########################################################
player:
  death: 
    enable: true  #是否开启死后灵魂模式的功能
    clearinv: false   #是否清空背包
    clearexp: false   #是否清空经验
    autorespawn: 180   #自动重生时间（即可以被拯救的时间）
  inventory: 
    enable: true   #是否开启背包限制功能
    lockSlots: 18  #初始锁定几格
  stats:
    autosave: 60   #自动保存玩家固有属性的周期
#世界设置##########################################################
world:
  blind: 
    up: 15000   #失明开始的时间（MC游戏刻）
    down: 23000   #失明结束的时间（MC游戏刻）
  darkness: 
    warnTime: 3   #在亮度为0的黑暗中停留几秒会警告
    attackTime: 7   #在亮度为0的黑暗中停留几秒会攻击
    darkDamage: 10   #在亮度为0的黑暗中停留attack秒后攻击的伤害
    sanWarn: -5   #在亮度为0的黑暗中停留warn秒后每秒影响的理智值
    sanAttack: -10   #在亮度为0的黑暗中停留attack秒后每秒影响的理智值
    carrotEffect: 10  #吃萝卜可以暂时免疫黑暗的秒数（金萝卜*5）
  season:
    spring: 30   #春天大约多少天（会有10天的随机浮动）
    autumn: 30   #秋天大约多少天（会有10天的随机浮动）
    summer: 20   #夏天大约多少天（会有10天的随机浮动）
    winter: 20   #冬天大约多少天（会有10天的随机浮动）
    
block:
  fresh: 60   #方块保存与读取的CD
disableWorlds:   #不启用插件的世界
- world_nether
