name: UntilTheEnd
main: HamsterYDS.UntilTheEnd.UntilTheEnd
version: 5.6
depend: [LibsDisguises,HolographicDisplays,PlaceholderAPI]
softdepend: [ProtocolLib,Multiverse-Core]
commands:
  ute:
    usage: /ute