name: UntilTheEnd
main: HamsterYDS.UntilTheEnd.UntilTheEnd
version: "5.6.5-Beta"
depend: [HolographicDisplays,PlaceholderAPI]
softdepend: [ProtocolLib,Multiverse-Core,LibsDisguises]
authors:
  - "南外丶仓鼠"
  - "瑞瑞瑞瑞阿"
  - "Karlatemp"
commands:
  ute:
    usage: /ute
#api-version: "1.13"