name: UntilTheEnd
main: HamsterYDS.UntilTheEnd.UntilTheEnd
version: 5.4
depend: [LibsDisguises,HolographicDisplays]
softdepend: [PlaceholderAPI,BossBarAPI,Multiverse-Core]
commands:
  ute:
    usage: /ute