name: UntilTheEnd
main: HamsterYDS.UntilTheEnd.UntilTheEnd
version: "Development"
softdepend:
  - PlaceholderAPI
  - ProtocolLib
  - Multiverse-Core
  - LibsDisguises
  - Citizens
  - Vault
authors:
  - "南外丶仓鼠"
  - "瑞瑞瑞瑞阿"
  - "Karlatemp"
commands:
  ute:
    usage: /ute
#api-version: "1.13"